//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrenyApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CurrencyRateEntities : DbContext
    {
        public CurrencyRateEntities()
            : base("name=CurrencyRateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblCurrency> TblCurrencies { get; set; }
        public virtual DbSet<TblCurrencyPrice> TblCurrencyPrices { get; set; }
        public virtual DbSet<TblOperation> TblOperations { get; set; }
    }
}
