//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrenyApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCurrencyPrice
    {
        public int preisId { get; set; }
        public Nullable<int> currencyName { get; set; }
        public Nullable<decimal> currencyBuying { get; set; }
        public Nullable<decimal> currencySelling { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual TblCurrency TblCurrency { get; set; }
    }
}
