//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrenyApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCurrency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCurrency()
        {
            this.TblCurrencyPrices = new HashSet<TblCurrencyPrice>();
            this.TblOperations = new HashSet<TblOperation>();
        }
    
        public int currencyId { get; set; }
        public string currencyName { get; set; }
        public string currnecySymbol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCurrencyPrice> TblCurrencyPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOperation> TblOperations { get; set; }
    }
}
