//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrenyApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOperation
    {
        public int operetionId { get; set; }
        public string customenrName { get; set; }
        public string customerSurname { get; set; }
        public Nullable<int> currencyCode { get; set; }
        public string operationType { get; set; }
        public Nullable<decimal> currentValue { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<System.DateTime> operationDate { get; set; }
    
        public virtual TblCurrency TblCurrency { get; set; }
    }
}
